In [2]:
import numpy as np
import pandas as pd
from numpy.linalg import eig
from numpy.linalg import eigvals
from scipy.sparse.linalg import eigs
from scipy.sparse.linalg import eigsh

In [ ]:
#

economy=pd.read_excel(r'D:\Personal\University\Master\Thesis\Aggregation-Weighting\AHP for weighting indicators\Expert answers\Analysis\AHP Questionnaire1.xlsx',sheet_name='اقتصاد',usecols='L:O')
economy=economy.dropna(how='all').reset_index(drop=True)

def AHP_Economy(economy):
    eco=[]
    inve1=economy.iloc[1:4,0:3]
    inve2=economy.iloc[5:7,0:2]
    inve3=economy.iloc[8:,0:3]

    e1=inve1*0
    for i in range(len(inve1.columns)):
        e1.iloc[:,i]=inve1.iloc[:,-(i+1)]
    e1=np.array(e1,dtype=float)
    eco.append(e1)

    e2=inve2*0
    for i in range(len(inve2.columns)):
        e2.iloc[:,i]=inve2.iloc[:,-(i+1)]
    e2=np.array(e2,dtype=float)
    eco.append(e2)

    e3=inve3*0
    for i in range(len(inve3.columns)):
        e3.iloc[:,i]=inve3.iloc[:,-(i+1)]
    e3=np.array(e3,dtype=float)
    eco.append(e3)

    weight_vector=[0]*len(eco)
    max_eigenvalue=[0]*len(eco)
    temp=[0,0]
    for i in range(len(eco)):  
        if len(eco[i])<3:
            temp[0]=eco[i][0,0]
            temp[1]=eco[i][1,0]
            weight_vector[i]=np.array(temp)
            max_eigenvalue[i]=2
        else:
            max_eigenvalue[i], weight_vector[i]=eigs(eco[i],k=1,which='LM')
            weight_vector[i]=np.transpose(abs(weight_vector[i].real))[0]     
            max_eigenvalue[i]=max_eigenvalue[i][0].real
        
    return (weight_vector,max_eigenvalue)

AHP_Economy(economy)


In [179]:
## economy dimension weighting with AHP

# reading data from excel files
economy=[]
address_string=[]
for i in range(3):
    address_string.append(r'D:\Personal\University\Master\Thesis\Aggregation-Weighting\AHP for weighting indicators\Expert answers\Analysis\AHP Questionnaire'+str(i+1)+'.xlsx')
    economy.append(pd.read_excel(address_string[i],sheet_name='اقتصاد',usecols='L:O').dropna(how='all').reset_index(drop=True))

# number of aggregation levels
n_hierarchy=3    
    
# defining function for estimating weights based on comparison matrices'
def AHP_Economy(economy):
    
    # cleaning data and correcting format problem caused by right to left layout in excel
    eco=[]
    inve_list=[]
    inve_list.append(economy.iloc[1:4,0:3])
    inve_list.append(economy.iloc[5:7,0:2])
    inve_list.append(economy.iloc[8:,0:3])

    for j in range(len(inve_list)):
        eco.append(inve_list[j]*0)
        for i in range(len(inve_list[j].columns)):
            eco[j].iloc[:,i]=inve_list[j].iloc[:,-(i+1)]
        eco[j]=np.array(eco[j],dtype=float)
    
    # calculating eigenvectors and eigenvalues of pairwise matrices'
    weight_vector=[0]*len(eco)
    max_eigenvalue=[0]*len(eco)
    temp=[0,0]
    n=[]
    for i in range(len(eco)):
        n.append(len(eco[i]))
        if len(eco[i])<3:
            temp[0]=eco[i][0,0]
            temp[1]=eco[i][1,0]
            weight_vector[i]=np.array(temp)
            max_eigenvalue[i]=2
        else:
            max_eigenvalue[i], weight_vector[i]=eigs(eco[i],k=1,which='LM')
            weight_vector[i]=np.transpose(abs(weight_vector[i].real))[0]     
            max_eigenvalue[i]=max_eigenvalue[i][0].real
        
    return (weight_vector,max_eigenvalue,n)

# defining function for calculating inconsistency ratio
def CR(max_eigenvalue,n):
    temp=0.0000
    if n>2 and n<4:
        temp=(max_eigenvalue-n)/(n-1)
        result=temp/0.52
    else:
        result=temp/0.89
    return result


CR_df_eco=pd.DataFrame(np.zeros((len(economy),n_hierarchy), dtype=float))

for i in range(len(economy)):
    weight_vector_eco[i]=AHP_Economy(economy[i])[0]
    max_eigenvalue_eco[i]=AHP_Economy(economy[i])[1]
    n_eco[i]=AHP_Economy(economy[i])[2]
    for j in range(len(max_eigenvalue_eco[i])):
        CR_df_eco.iloc[i,j]=(CR(max_eigenvalue_eco[i][j],n_eco[i][j]))
    for k in range(len(weight_vector_eco)):
        weight_vector_eco[i][k]=weight_vector_eco[i][k]/weight_vector_eco[i][k].sum()

    


[[array([0.25828499, 0.10472943, 0.63698557]),
  array([0.875, 0.125]),
  array([0.73830738, 0.17017232, 0.0915203 ])],
 [array([0.33333333, 0.11111111, 0.55555556]),
  array([0.83333333, 0.16666667]),
  array([0.33203155, 0.16657288, 0.50139556])],
 [array([0.63698557, 0.25828499, 0.10472943]),
  array([0.875, 0.125]),
  array([0.78539119, 0.06579374, 0.14881507])]]